<?php
/**
 * Created by Artdevue.
 * User: artdevue - GamesLikesController.php
 * Date: 2020-02-02
 * Time: 12:50
 * Project: gamesgo.club
 */

namespace App\Http\Controllers;


class GamesLikesController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        //$this->middleware('auth');
        parent::__construct(); // TODO: Change the autogenerated stub
    }


}